### ISSUE TITLE
npm install task is running iOS tests

### ISSUE THREAD

**Issue by prolificcoder** [appium/appium-android-driver#115]
A snippet of my log when running npm install on this project

```shell
> fsevents@1.0.8 install /Users/malugus/Code/appium-android-driver/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/malugus/Code/appium-android-driver/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote

> ios-webview-app@1.0.3 install /Users/malugus/Code/appium-android-driver/node_modules/ios-webview-app
> node -e "require('grunt').tasks(['default']);"

Running "cleanAll" task

Running "clean:iphonesimulator9.2" (clean) task

Running "clean:iphoneos9.2" (clean) task

Running "buildAll" task

Running "build:iphonesimulator9.2" (build) task
Building app...done building ios app for idk iphonesimulator9.2
Running "build:iphoneos9.2" (build) task
Building app...>> Failed building app
>> Build settings from command line:
>>     SDKROOT = iphoneos9.2
>> 
>> === BUILD TARGET WebViewApp OF PROJECT WebViewApp WITH THE DEFAULT CONFIGURATION (Release) ===
>> 
>> Check dependencies
>> Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.
>> 
>> ** BUILD FAILED **
>> 
>> 
>> The following build commands failed:
>> 	Check dependencies
>> (1 failure)

Running "renameAll" task

> ios-uicatalog@1.0.2 install /Users/malugus/Code/appium-android-driver/node_modules/ios-uicatalog
> node -e "require('grunt').tasks(['default']);"

Running "cleanAll" task

Running "clean:iphonesimulator9.2" (clean) task

Running "clean:iphoneos9.2" (clean) task

Running "buildAll" task

Running "build:iphonesimulator9.2" (build) task
Building app...done building ios app for idk iphonesimulator9.2
Running "build:iphoneos9.2" (build) task
Building app...>> Failed building app
>> Build settings from command line:
>>     SDKROOT = iphoneos9.2
>> 
>> === BUILD TARGET UICatalog OF PROJECT UICatalog WITH THE DEFAULT CONFIGURATION (Release) ===
>> 
>> Check dependencies
>> Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.
>> 
>> ** BUILD FAILED **
>> 
>> 
>> The following build commands failed:
>> 	Check dependencies
>> (1 failure)

Running "renameAll" task

> ios-test-app@2.3.4 install /Users/malugus/Code/appium-android-driver/node_modules/ios-test-app
> ./build-js/install.js

info iOSTestApp cleaning apps
dbug iOSTestApp cleaning app for iphonesimulator9.2
dbug iOSTestApp cleaning app for iphoneos9.2
info iOSTestApp finished cleaning apps
info iOSTestApp building apps
dbug iOSTestApp building app for iphonesimulator9.2
dbug iOSTestApp building app for iphoneos9.2
ERR! iOSTestApp Error: Command 'xcodebuild -sdk iphoneos9.2' exited with code 65
ERR! iOSTestApp     at ChildProcess.<anonymous> (lib/teen_process.js:56:19)
ERR! iOSTestApp     at emitTwo (events.js:100:13)
ERR! iOSTestApp     at ChildProcess.emit (events.js:185:7)
ERR! iOSTestApp     at maybeClose (internal/child_process.js:827:16)
ERR! iOSTestApp     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
ERR! iOSTestApp  { [Error: Command 'xcodebuild -sdk iphoneos9.2' exited with code 65]
ERR! iOSTestApp   stdout: 'Build settings from command line:\n    SDKROOT = iphoneos9.2\n\n=== BUILD TARGET TestApp OF PROJECT TestApp WITH THE DEFAULT CONFIGURATION (Release) ===\n\nCheck dependencies\nCode Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.\n\n',
ERR! iOSTestApp   stderr: '** BUILD FAILED **\n\n\nThe following build commands failed:\n\tCheck dependencies\n(1 failure)\n',
ERR! iOSTestApp   code: 65 }
info iOSTestApp finished building apps
info iOSTestApp renaming apps
WARN iOSTestApp could not rename apps
ERR! iOSTestApp Error: ENOENT: no such file or directory, rename '/Users/malugus/Code/appium-android-driver/node_modules/ios-test-app/build/Release-iphoneos/TestApp.app' -> '/Users/malugus/Code/appium-android-driver/node_modules/ios-test-app/build/Release-iphoneos/TestApp-iphoneos.app'
ERR! iOSTestApp     at Error (native)
ERR! iOSTestApp  { [Error: ENOENT: no such file or directory, rename '/Users/malugus/Code/appium-android-driver/node_modules/ios-test-app/build/Release-iphoneos/TestApp.app' -> '/Users/malugus/Code/appium-android-driver/node_modules/ios-test-app/build/Release-iphoneos/TestApp-iphoneos.app']
ERR! iOSTestApp   cause: 
ERR! iOSTestApp    { [Error: ENOENT: no such file or directory, rename '/Users/malugus/Code/appium-android-driver/node_modules/ios-test-app/build/Release-iphoneos/TestApp.app' -> '/Users/malugus/Code/appium-android-driver/node_modules/ios-test-app/build/Release-iphoneos/TestApp-iphoneos.app']
ERR! iOSTestApp      errno: -2,
ERR! iOSTestApp      code: 'ENOENT',
ERR! iOSTestApp      syscall: 'rename',
ERR! iOSTestApp      path: '/Users/malugus/Code/appium-android-driver/node_modules/ios-test-app/build/Release-iphoneos/TestApp.app',
ERR! iOSTestApp      dest: '/Users/malugus/Code/appium-android-driver/node_modules/ios-test-app/build/Release-iphoneos/TestApp-iphoneos.app' },
ERR! iOSTestApp   isOperational: true,
ERR! iOSTestApp   errno: -2,
ERR! iOSTestApp   code: 'ENOENT',
ERR! iOSTestApp   syscall: 'rename',
ERR! iOSTestApp   path: '/Users/malugus/Code/appium-android-driver/node_modules/ios-test-app/build/Release-iphoneos/TestApp.app',
ERR! iOSTestApp   dest: '/Users/malugus/Code/appium-android-driver/node_modules/ios-test-app/build/Release-iphoneos/TestApp-iphoneos.app' }

> appium-chromedriver@2.8.0 install /Users/malugus/Code/appium-android-driver/node_modules/appium-chromedriver
> node install-npm.js
```

**Comment by imurchie** [comment]
These aren't tests, it is trying to build the test apps. We have not yet had time to conditionally install them.
