### ISSUE TITLE
npm run watch failed

### ISSUE THREAD

**Issue by valaxy** [appium/appium-android-driver#80]
After `git clone` and run `npm run watch`, I don't know why, need help

```
λ npm run watch

> appium-android-driver@1.3.3 watch C:\Project\x5-driver\build\hook\appium-android-driver
> gulp

[16:25:38] Using gulpfile C:\Project\x5-driver\build\hook\appium-android-driver\gulpfile.js
[16:25:38] Starting 'watch'...
[16:25:38] Finished 'watch' after 5.33 ms
[16:25:38] Starting 'default'...
[16:25:38] Finished 'default' after 5.42 μs
Error: spawn C:\Project\x5-driver\build\hook\appium-android-driver\node_modules\.bin\gulp ENOENT
    at exports._errnoException (util.js:855:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Software\\nodejs\\node.exe" "C:\\Users\\tianyuzou\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! appium-android-driver@1.3.3 watch: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-android-driver@1.3.3 watch script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-android-driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-android-driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-android-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Project\x5-driver\build\hook\appium-android-driver\npm-debug.log
```

**Comment by Jonahss** [comment]
install `gulp` and `gulp-cli` globally.
`npm install -g gulp gulp-cli`

Should fix it.

@jlipps We should add a note about these dependencies to a development doc.

**Comment by jlipps** [comment]
https://github.com/appium/appium/commit/86e3685083e2b22f46ec4ef0d53eacb579d4e5fc
